package com.gsc.model;
// Generated Jun 5, 2021, 2:32:58 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Categorie generated by hbm2java
 */
@Entity
@Table(name = "categorie", catalog = "gcommande")
public class Categorie implements java.io.Serializable {

	private Integer catId;
	private String libeleCat;

	public Categorie() {
	}

	public Categorie(String libeleCat) {
		this.libeleCat = libeleCat;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CatId", unique = true, nullable = false)
	public Integer getCatId() {
		return this.catId;
	}

	public void setCatId(Integer catId) {
		this.catId = catId;
	}

	@Column(name = "LibeleCat", nullable = false)
	public String getLibeleCat() {
		return this.libeleCat;
	}

	public void setLibeleCat(String libeleCat) {
		this.libeleCat = libeleCat;
	}

	@Override
	public String toString() {
		return "Categorie [catId=" + catId + ", libeleCat=" + libeleCat + "]";
	}
	
	
	

}
