package com.gsc.model;
// Generated Jun 5, 2021, 2:32:58 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "client", catalog = "gcommande")
public class Client implements java.io.Serializable {

	private Integer idClient;
	private String numTel;
	private String nom;
	private String prenom;
	private String email;
	private String sexe;

	public Client() {
	}

	public Client(String numTel, String nom, String prenom, String email, String sexe) {
		this.numTel = numTel;
		this.nom = nom;
		this.prenom = prenom;
		this.email = email;
		this.sexe = sexe;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_client", unique = true, nullable = false)
	public Integer getIdClient() {
		return this.idClient;
	}

	public void setIdClient(Integer idClient) {
		this.idClient = idClient;
	}
	
	@Column(name = "Num_tel", length = 65535)
	public String getNumTel() {
		return this.numTel;
	}

	public void setNumTel(String numTel) {
		this.numTel = numTel;
	}

	@Column(name = "nom", length = 65535)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", length = 65535)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "email", length = 65535)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "sexe", length = 65535)
	public String getSexe() {
		return this.sexe;
	}

	public void setSexe(String sexe) {
		this.sexe = sexe;
	}

	@Override
	public String toString() {
		return "Client [idClient=" + idClient + ", numTel=" + numTel + ", nom=" + nom
				+ ", prenom=" + prenom + ", email=" + email + ", sexe=" + sexe + "]";
	}

	
	
}
