package com.gsc.model;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Commande generated by hbm2java
 */
@Entity
@Table(name = "commande", catalog = "gcommande")
public class Commande implements java.io.Serializable {

	private Integer idCommande;
	private int idProduit;
	private int idclient;
	private int idUser;
	private String adresse;
	private Integer quantite;
	private String dateCommande;

	public Commande() {
	}

	public Commande(int idProduit, int idclient, int idUser) {
		this.idProduit = idProduit;
		this.idclient = idclient;
		this.idUser = idUser;
	}

	public Commande(int idProduit, int idclient, int idUser, String adresse, Integer quantite, String dateCommande) {
		this.idProduit = idProduit;
		this.idclient = idclient;
		this.idUser = idUser;
		this.adresse = adresse;
		this.quantite = quantite;
		this.dateCommande = dateCommande;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_commande", unique = true, nullable = false)
	public Integer getIdCommande() {
		return this.idCommande;
	}

	public void setIdCommande(Integer idCommande) {
		this.idCommande = idCommande;
	}

	@Column(name = "id_produit", nullable = false)
	public int getIdProduit() {
		return this.idProduit;
	}

	public void setIdProduit(int idProduit) {
		this.idProduit = idProduit;
	}

	@Column(name = "idclient", nullable = false)
	public int getIdclient() {
		return this.idclient;
	}

	public void setIdclient(int idclient) {
		this.idclient = idclient;
	}

	@Column(name = "idUser", nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@Column(name = "adresse", length = 65535)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "quantite")
	public Integer getQuantite() {
		return this.quantite;
	}

	public void setQuantite(Integer quantite) {
		this.quantite = quantite;
	}

	@Column(name = "date_commande", length = 65535)
	public String getDateCommande() {
		return this.dateCommande;
	}

	public void setDateCommande(String dateCommande) {
		this.dateCommande = dateCommande;
	}

	@Override
	public String toString() {
		return "Commande [idCommande=" + idCommande + ", idProduit=" + idProduit + ", idclient=" + idclient
				+ ", idUser=" + idUser + ", adresse=" + adresse + ", quantite=" + quantite + ", dateCommande="
				+ dateCommande + "]";
	}

	
}
