package com.gsc.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Produit generated by hbm2java
 */
@Entity
@Table(name = "produit", catalog = "gcommande")
public class Produit implements java.io.Serializable {

	private Integer produitId;
	private String libele;
	private int categorieId;
	private double prix;

	public Produit() {
	}

	public Produit(String libele, int categorieId, double prix) {
		this.libele = libele;
		this.categorieId = categorieId;
		this.prix = prix;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ProduitId", unique = true, nullable = false)
	public Integer getProduitId() {
		return this.produitId;
	}

	public void setProduitId(Integer produitId) {
		this.produitId = produitId;
	}

	@Column(name = "Libele", nullable = false)
	public String getLibele() {
		return this.libele;
	}

	public void setLibele(String libele) {
		this.libele = libele;
	}

	@Column(name = "CategorieId", nullable = false)
	public int getCategorieId() {
		return this.categorieId;
	}

	public void setCategorieId(int categorieId) {
		this.categorieId = categorieId;
	}

	@Column(name = "Prix", nullable = false, precision = 22, scale = 0)
	public double getPrix() {
		return this.prix;
	}

	public void setPrix(double prix) {
		this.prix = prix;
	}

	@Override
	public String toString() {
		return "Produit [produitId=" + produitId + ", libele=" + libele + ", categorieId=" + categorieId + ", prix="
				+ prix + "]";
	}

	
}
